/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.51 from the
 * contents of SPI.xs. Do not edit this file, edit SPI.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

///////////////////////////////////////////////////////////////////////////////////////
// File          SPI.xs
// Description:  XS module for HiPi::Device::SPI
// Copyright:    Copyright (c) 2013-2017 Mark Dootson
// License:      This is free software; you can redistribute it and/or modify it under
//               the same terms as the Perl 5 programming language system itself.
///////////////////////////////////////////////////////////////////////////////////////

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "mylib/include/ppport.h"
#include <sys/ioctl.h>
#include <linux/spi/spidev.h>

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%" UVxf ")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif


XS_EUPXS(XS_HiPi__Device__SPI__transfer_data); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Device__SPI__transfer_data)
{
    dVAR; dXSARGS;
    if (items < 2 || items > 5)
       croak_xs_usage(cv,  "file, inbuf, delay = 0, speed = 1000000, bitspw = 8");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	file = (int)SvIV(ST(0))
;
	SV*	inbuf = ST(1)
;
	__u16	delay;
	__u32	speed;
	__u8	bitspw;

	if (items < 3)
	    delay = 0;
	else {
	    delay = (unsigned short)SvUV(ST(2))
;
	}

	if (items < 4)
	    speed = 1000000;
	else {
	    speed = (__u32)SvUV(ST(3))
;
	}

	if (items < 5)
	    bitspw = 8;
	else {
	    bitspw = (__u8)SvUV(ST(4))
;
	}
    struct spi_ioc_transfer msg;
    memset (&msg, 0, sizeof(msg));
    SV* outbuf = newSVsv(inbuf);

    msg.tx_buf        = (intptr_t)SvPVX(inbuf);
    msg.rx_buf        = (intptr_t)SvPVX(outbuf);
    msg.len           = (__u32)SvCUR(inbuf);
    msg.speed_hz      = speed;
    msg.delay_usecs   = delay;
    msg.bits_per_word = bitspw;


    int ioval = ioctl (file, SPI_IOC_MESSAGE(1), &msg);
    if( ioval >= 0)
    {
        EXTEND(SP, 1);
        PUSHs(sv_2mortal(outbuf));
    }
    else
    {
        EXTEND(SP, 1);
        PUSHs(&PL_sv_undef);
    }
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_HiPi__Device__SPI__set_spi_max_speed); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Device__SPI__set_spi_max_speed)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "file, speed");
    {
	int	file = (int)SvIV(ST(0))
;
	__u32	speed = (__u32)SvUV(ST(1))
;
	int	RETVAL;
	dXSTARG;
    int rval;
    rval = ioctl(file, SPI_IOC_WR_MAX_SPEED_HZ, &speed);
    if( rval < 0 )
        rval = -1;

    RETVAL = rval;
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Device__SPI__get_spi_max_speed); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Device__SPI__get_spi_max_speed)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "file");
    {
	int	file = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;
    __u32 speed;
    int rval;
    rval = ioctl(file, SPI_IOC_RD_MAX_SPEED_HZ, &speed);

    if( rval < 0 ) {
        RETVAL = -1;
    } else {
        RETVAL = speed;
    }

	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Device__SPI__set_spi_mode); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Device__SPI__set_spi_mode)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "file, mode");
    {
	int	file = (int)SvIV(ST(0))
;
	__u8	mode = (__u8)SvUV(ST(1))
;
	int	RETVAL;
	dXSTARG;
    int rval;
    rval = ioctl(file, SPI_IOC_WR_MODE, &mode);

    if( rval < 0 )
        rval = -1;

    RETVAL = rval;
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Device__SPI__get_spi_mode); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Device__SPI__get_spi_mode)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "file");
    {
	int	file = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;
    int rval;
    __u8 mode;
    rval = ioctl(file, SPI_IOC_RD_MODE, &mode);
    if( rval < 0 ) {
        RETVAL = -1;
    } else {
        RETVAL = mode;
    }
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Device__SPI__set_spi_bits_per_word); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Device__SPI__set_spi_bits_per_word)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "file, bitspw");
    {
	int	file = (int)SvIV(ST(0))
;
	__u8	bitspw = (__u8)SvUV(ST(1))
;
	int	RETVAL;
	dXSTARG;
    int rval;
    rval = ioctl(file, SPI_IOC_WR_BITS_PER_WORD, &bitspw);

    if( rval < 0 )
        rval = -1;

    RETVAL = rval;
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_HiPi__Device__SPI__get_spi_bits_per_word); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_HiPi__Device__SPI__get_spi_bits_per_word)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "file");
    {
	int	file = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;
    int rval;
    __u8 bitspw;
    rval = ioctl(file, SPI_IOC_RD_BITS_PER_WORD, &bitspw);
    if( rval < 0 ) {
        RETVAL = -1;
    } else {
        RETVAL = bitspw;
    }
	XSprePUSH;
	PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C" {
#endif
XS_EXTERNAL(boot_HiPi__Device__SPI); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_HiPi__Device__SPI)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if PERL_VERSION_LE(5, 8, 999) /* PERL_VERSION_LT is 5.33+ */
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("HiPi::Device::SPI::_transfer_data", XS_HiPi__Device__SPI__transfer_data);
        newXS_deffile("HiPi::Device::SPI::_set_spi_max_speed", XS_HiPi__Device__SPI__set_spi_max_speed);
        newXS_deffile("HiPi::Device::SPI::_get_spi_max_speed", XS_HiPi__Device__SPI__get_spi_max_speed);
        newXS_deffile("HiPi::Device::SPI::_set_spi_mode", XS_HiPi__Device__SPI__set_spi_mode);
        newXS_deffile("HiPi::Device::SPI::_get_spi_mode", XS_HiPi__Device__SPI__get_spi_mode);
        newXS_deffile("HiPi::Device::SPI::_set_spi_bits_per_word", XS_HiPi__Device__SPI__set_spi_bits_per_word);
        newXS_deffile("HiPi::Device::SPI::_get_spi_bits_per_word", XS_HiPi__Device__SPI__get_spi_bits_per_word);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

#ifdef __cplusplus
}
#endif
